document.write('<style>');
document.write('#katakana-table td, #hirakana-table td {');
document.write('    border: 1px solid black;');
document.write('    border-radius: 5px;');
document.write('    padding-left: 20;');
document.write('    padding-right: 20;');
document.write('    text-align: center;');
document.write('}');
document.write('#katakana-table th, #hirakana-table th {');
document.write('    border: 1px solid black;');
document.write('    border-radius: 5px;');
document.write('    padding-left: 20;');
document.write('    padding-right: 20;');
document.write('}');
document.write('#katakana-table, #hirakana-table{');
document.write('    padding-left: 10px;');
document.write('    padding-right: 10px;');
document.write('}');
document.write('</style>');
document.write('');
document.write('<table id="hirakana-table" style="display:inline;">');
document.write('    <tr>');
document.write('        <th>あ段</th>');
document.write('        <th>い段</th>');
document.write('        <th>う段</th>');
document.write('        <th>え段</th>');
document.write('        <th>お段</th>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>あ</td>');
document.write('        <td>い</td>');
document.write('        <td>う</td>');
document.write('        <td>え</td>');
document.write('        <td>お</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>か</td>');
document.write('        <td>き</td>');
document.write('        <td>く</td>');
document.write('        <td>け</td>');
document.write('        <td>こ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>さ</td>');
document.write('        <td>し</td>');
document.write('        <td>す</td>');
document.write('        <td>せ</td>');
document.write('        <td>そ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>た</td>');
document.write('        <td>ち</td>');
document.write('        <td>つ</td>');
document.write('        <td>て</td>');
document.write('        <td>と</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>な</td>');
document.write('        <td>に</td>');
document.write('        <td>ぬ</td>');
document.write('        <td>ね</td>');
document.write('        <td>の</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>は</td>');
document.write('        <td>ひ</td>');
document.write('        <td>ふ</td>');
document.write('        <td>へ</td>');
document.write('        <td>ほ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ま</td>');
document.write('        <td>み</td>');
document.write('        <td>む</td>');
document.write('        <td>め</td>');
document.write('        <td>も</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>や</td>');
document.write('        <td>　</td>');
document.write('        <td>ゆ</td>');
document.write('        <td>　</td>');
document.write('        <td>よ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ら</td>');
document.write('        <td>り</td>');
document.write('        <td>る</td>');
document.write('        <td>れ</td>');
document.write('        <td>ろ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>わ</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>を</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ん</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('    </tr>');
document.write('</table>');
document.write('');
document.write('<table id="katakana-table" style="display:inline;">');
document.write('    <tr>');
document.write('        <th>ア段</th>');
document.write('        <th>イ段</th>');
document.write('        <th>ウ段</th>');
document.write('        <th>エ段</th>');
document.write('        <th>オ段</th>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ア</td>');
document.write('        <td>イ</td>');
document.write('        <td>ウ</td>');
document.write('        <td>エ</td>');
document.write('        <td>オ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>カ</td>');
document.write('        <td>キ</td>');
document.write('        <td>ク</td>');
document.write('        <td>ケ</td>');
document.write('        <td>コ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>サ</td>');
document.write('        <td>シ</td>');
document.write('        <td>ス</td>');
document.write('        <td>セ</td>');
document.write('        <td>ソ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>タ</td>');
document.write('        <td>チ</td>');
document.write('        <td>ツ</td>');
document.write('        <td>テ</td>');
document.write('        <td>ト</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ナ</td>');
document.write('        <td>ニ</td>');
document.write('        <td>ヌ</td>');
document.write('        <td>ネ</td>');
document.write('        <td>ノ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ハ</td>');
document.write('        <td>ヒ</td>');
document.write('        <td>フ</td>');
document.write('        <td>ヘ</td>');
document.write('        <td>ホ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>マ</td>');
document.write('        <td>ミ</td>');
document.write('        <td>ム</td>');
document.write('        <td>メ</td>');
document.write('        <td>モ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ヤ</td>');
document.write('        <td> </td>');
document.write('        <td>ユ</td>');
document.write('        <td>　</td>');
document.write('        <td>ヨ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ラ</td>');
document.write('        <td>リ</td>');
document.write('        <td>ル</td>');
document.write('        <td>レ</td>');
document.write('        <td>ロ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ワ</td>');
document.write('        <td> </td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>ヲ</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ン</td>');
document.write('        <td> </td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('    </tr>');
document.write('</table>');
document.write('');
document.write('<table id="eiji-table" style="display:inline; visibility: hidden;">');
document.write('    <tr>');
document.write('        <th>あ段</th>');
document.write('        <th>い段</th>');
document.write('        <th>う段</th>');
document.write('        <th>え段</th>');
document.write('        <th>お段</th>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>a</td>');
document.write('        <td>i</td>');
document.write('        <td>u</td>');
document.write('        <td>e</td>');
document.write('        <td>o</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ka</td>');
document.write('        <td>ki</td>');
document.write('        <td>ku</td>');
document.write('        <td>ke</td>');
document.write('        <td>ko</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>sa</td>');
document.write('        <td>shi</td>');
document.write('        <td>su</td>');
document.write('        <td>se</td>');
document.write('        <td>so</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ta</td>');
document.write('        <td>chi</td>');
document.write('        <td>tsu</td>');
document.write('        <td>te</td>');
document.write('        <td>to</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>na</td>');
document.write('        <td>ni</td>');
document.write('        <td>nu</td>');
document.write('        <td>ne</td>');
document.write('        <td>no</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ha</td>');
document.write('        <td>hi</td>');
document.write('        <td>fu</td>');
document.write('        <td>he</td>');
document.write('        <td>ho</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ma</td>');
document.write('        <td>mi</td>');
document.write('        <td>mu</td>');
document.write('        <td>me</td>');
document.write('        <td>mo</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ya</td>');
document.write('        <td>　</td>');
document.write('        <td>yu</td>');
document.write('        <td>　</td>');
document.write('        <td>yo</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>ra</td>');
document.write('        <td>ri</td>');
document.write('        <td>ru</td>');
document.write('        <td>re</td>');
document.write('        <td>ro</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>wa</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>wo</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>nn</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('        <td>　</td>');
document.write('    </tr>');
document.write('</table>');
