document.writeln("<style>");
document.writeln("#katakana-table td, #hirakana-table td {");
document.writeln("    border: 1px solid black;");
document.writeln("    border-radius: 5px;");
document.writeln("    padding-left: 20;");
document.writeln("    padding-right: 20;");
document.writeln("    text-align: center;");
document.writeln("}");
document.writeln("#katakana-table th, #hirakana-table th {");
document.writeln("    border: 1px solid black;");
document.writeln("    border-radius: 5px;");
document.writeln("    padding-left: 20;");
document.writeln("    padding-right: 20;");
document.writeln("}");
document.writeln("#katakana-table, #hirakana-table{");
document.writeln("    padding-left: 10px;");
document.writeln("    padding-right: 10px;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<table id=\"hirakana-table\" style=\"display:inline;\">");
document.writeln("    <tr>");
document.writeln("        <th>あ段</th>");
document.writeln("        <th>い段</th>");
document.writeln("        <th>う段</th>");
document.writeln("        <th>え段</th>");
document.writeln("        <th>お段</th>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>あ</td>");
document.writeln("        <td>い</td>");
document.writeln("        <td>う</td>");
document.writeln("        <td>え</td>");
document.writeln("        <td>お</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>か</td>");
document.writeln("        <td>き</td>");
document.writeln("        <td>く</td>");
document.writeln("        <td>け</td>");
document.writeln("        <td>こ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>さ</td>");
document.writeln("        <td>し</td>");
document.writeln("        <td>す</td>");
document.writeln("        <td>せ</td>");
document.writeln("        <td>そ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>た</td>");
document.writeln("        <td>ち</td>");
document.writeln("        <td>つ</td>");
document.writeln("        <td>て</td>");
document.writeln("        <td>と</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>な</td>");
document.writeln("        <td>に</td>");
document.writeln("        <td>ぬ</td>");
document.writeln("        <td>ね</td>");
document.writeln("        <td>の</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>は</td>");
document.writeln("        <td>ひ</td>");
document.writeln("        <td>ふ</td>");
document.writeln("        <td>へ</td>");
document.writeln("        <td>ほ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ま</td>");
document.writeln("        <td>み</td>");
document.writeln("        <td>む</td>");
document.writeln("        <td>め</td>");
document.writeln("        <td>も</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>や</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>ゆ</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>よ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ら</td>");
document.writeln("        <td>り</td>");
document.writeln("        <td>る</td>");
document.writeln("        <td>れ</td>");
document.writeln("        <td>ろ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>わ</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>を</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ん</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>　</td>");
document.writeln("    </tr>");
document.writeln("</table>");
document.writeln("");
document.writeln("<table id=\"katakana-table\" style=\"display:inline;\">");
document.writeln("    <tr>");
document.writeln("        <th>ア段</th>");
document.writeln("        <th>イ段</th>");
document.writeln("        <th>ウ段</th>");
document.writeln("        <th>エ段</th>");
document.writeln("        <th>オ段</th>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ア</td>");
document.writeln("        <td>イ</td>");
document.writeln("        <td>ウ</td>");
document.writeln("        <td>エ</td>");
document.writeln("        <td>オ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>カ</td>");
document.writeln("        <td>キ</td>");
document.writeln("        <td>ク</td>");
document.writeln("        <td>ケ</td>");
document.writeln("        <td>コ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>サ</td>");
document.writeln("        <td>シ</td>");
document.writeln("        <td>ス</td>");
document.writeln("        <td>セ</td>");
document.writeln("        <td>ソ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>タ</td>");
document.writeln("        <td>チ</td>");
document.writeln("        <td>ツ</td>");
document.writeln("        <td>テ</td>");
document.writeln("        <td>ト</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ナ</td>");
document.writeln("        <td>ニ</td>");
document.writeln("        <td>ヌ</td>");
document.writeln("        <td>ネ</td>");
document.writeln("        <td>ノ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ハ</td>");
document.writeln("        <td>ヒ</td>");
document.writeln("        <td>フ</td>");
document.writeln("        <td>ヘ</td>");
document.writeln("        <td>ホ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>マ</td>");
document.writeln("        <td>ミ</td>");
document.writeln("        <td>ム</td>");
document.writeln("        <td>メ</td>");
document.writeln("        <td>モ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ヤ</td>");
document.writeln("        <td> </td>");
document.writeln("        <td>ユ</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>ヨ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ラ</td>");
document.writeln("        <td>リ</td>");
document.writeln("        <td>ル</td>");
document.writeln("        <td>レ</td>");
document.writeln("        <td>ロ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ワ</td>");
document.writeln("        <td> </td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>ヲ</td>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <td>ン</td>");
document.writeln("        <td> </td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>　</td>");
document.writeln("        <td>　</td>");
document.writeln("    </tr>");
document.writeln("</table>");