document.write('<style>');
document.write('    #verbTable td {');
document.write('        border: 1px solid black;');
document.write('        border-radius: 5px;');
document.write('        padding-left: 20;');
document.write('        padding-right: 20;');
document.write('        text-align: center;');
document.write('    }');
document.write('    #verbTable td.verbType {');
document.write('        border: none;');
document.write('        font-weight: bold;');
document.write('        color: red;');
document.write('    }');
document.write('');
document.write('    #verbTable th {');
document.write('        border-radius: 5px;');
document.write('        padding-left: 20;');
document.write('        padding-right: 20;');
document.write('        text-align: center;');
document.write('        font-weight: bold;');
document.write('    }');
document.write('    #verbTable{');
document.write('        table-layout: fixed;');
document.write('        border: 1px double black;');
document.write('        padding-left: 10px;');
document.write('        padding-right: 10px;');
document.write('        margin-left: auto;');
document.write('        margin-right: auto;');
document.write('    }');
document.write('</style>');
document.write('    ');
document.write('<table id="verbTable">');
document.write('    <tr>');
document.write('        <th>ます形</th>');
document.write('        <th>基本形</th>');
document.write('        <th>ない形</th>');
document.write('        <th>て形</th>');
document.write('        <th>命令形</th>');
document.write('        <th>可能形</th>');
document.write('        <th>仮定形</th>');
document.write('        <th>意志形</th>');
document.write('        <th>受動形</th>');
document.write('        <th>使役形</th>');
document.write('    </tr>');
document.write('    <tr><td class="verbType">一類動詞</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>会います</td>');
document.write('        <td>会う</td>');
document.write('        <td>会わない</td>');
document.write('        <td>会って</td>');
document.write('        <td>会え</td>');
document.write('        <td>会える</td>');
document.write('        <td>会えば</td>');
document.write('        <td>会おう</td>');
document.write('        <td>会われる</td>');
document.write('        <td>会わせる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>歩きます</td>');
document.write('        <td>歩く</td>');
document.write('        <td>歩かない</td>');
document.write('        <td>歩いて</td>');
document.write('        <td>歩け</td>');
document.write('        <td>歩ける</td>');
document.write('        <td>歩けば</td>');
document.write('        <td>歩こう</td>');
document.write('        <td>歩かれる</td>');
document.write('        <td>歩かせる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>脱ぎます</td>');
document.write('        <td>脱ぐ</td>');
document.write('        <td>脱がない</td>');
document.write('        <td>脱いで</td>');
document.write('        <td>脱げ</td>');
document.write('        <td>脱げる</td>');
document.write('        <td>脱げば</td>');
document.write('        <td>脱ごう</td>');
document.write('        <td>脱がれる</td>');
document.write('        <td>脱がせる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>話します</td>');
document.write('        <td>話す</td>');
document.write('        <td>話さない</td>');
document.write('        <td>話して</td>');
document.write('        <td>話せ</td>');
document.write('        <td>話せる</td>');
document.write('        <td>話せば</td>');
document.write('        <td>話そう</td>');
document.write('        <td>話される</td>');
document.write('        <td>話させる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>待ちます</td>');
document.write('        <td>待つ</td>');
document.write('        <td>待たない</td>');
document.write('        <td>待って</td>');
document.write('        <td>待て</td>');
document.write('        <td>待てる</td>');
document.write('        <td>待てば</td>');
document.write('        <td>待とう</td>');
document.write('        <td>待たれる</td>');
document.write('        <td>待たせる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>死にます</td>');
document.write('        <td>死ぬ</td>');
document.write('        <td>死なない</td>');
document.write('        <td>死んで</td>');
document.write('        <td>死ね</td>');
document.write('        <td>死ねる</td>');
document.write('        <td>死ねば</td>');
document.write('        <td>死のう</td>');
document.write('        <td>死なれる</td>');
document.write('        <td>死なせる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>飛びます</td>');
document.write('        <td>飛ぶ</td>');
document.write('        <td>飛ばない</td>');
document.write('        <td>飛んで</td>');
document.write('        <td>飛べ</td>');
document.write('        <td>飛べる</td>');
document.write('        <td>飛べば</td>');
document.write('        <td>飛ぼう</td>');
document.write('        <td>飛ばれる</td>');
document.write('        <td>飛ばせる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>沈みます</td>');
document.write('        <td>沈む</td>');
document.write('        <td>沈まない</td>');
document.write('        <td>沈んで</td>');
document.write('        <td>沈め</td>');
document.write('        <td>沈める</td>');
document.write('        <td>沈めば</td>');
document.write('        <td>沈もう</td>');
document.write('        <td>沈まれる</td>');
document.write('        <td>沈ませる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>走ります</td>');
document.write('        <td>走る</td>');
document.write('        <td>走らない</td>');
document.write('        <td>走って</td>');
document.write('        <td>走れ</td>');
document.write('        <td>走れる</td>');
document.write('        <td>走れば</td>');
document.write('        <td>走ろう</td>');
document.write('        <td>走れる</td>');
document.write('        <td>走らせる</td>');
document.write('    </tr>');
document.write('    <tr><td class="verbType">二類動詞</td></tr>');
document.write('    <tr>');
document.write('        <td>起きます</td>');
document.write('        <td>起きる</td>');
document.write('        <td>起きない</td>');
document.write('        <td>起きて</td>');
document.write('        <td>起きろ</td>');
document.write('        <td>起きられる</td>');
document.write('        <td>起きれば</td>');
document.write('        <td>起きよう</td>');
document.write('        <td>起きられる</td>');
document.write('        <td>起きさせる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>食べます</td>');
document.write('        <td>食べる</td>');
document.write('        <td>食べない</td>');
document.write('        <td>食べて</td>');
document.write('        <td>食べろ</td>');
document.write('        <td>食べられる</td>');
document.write('        <td>食べれば</td>');
document.write('        <td>食べよう</td>');
document.write('        <td>食べられる</td>');
document.write('        <td>食べさせる</td>');
document.write('    </tr>');
document.write('    <tr><td class="verbType">特殊動詞</td></tr>');
document.write('    <tr>');
document.write('        <td>きます</td>');
document.write('        <td>くる</td>');
document.write('        <td>こない</td>');
document.write('        <td>きて</td>');
document.write('        <td>こい</td>');
document.write('        <td>こられる</td>');
document.write('        <td>くれば</td>');
document.write('        <td>こよう</td>');
document.write('        <td>こられる</td>');
document.write('        <td>こさせる</td>');
document.write('    </tr>');
document.write('    <tr>');
document.write('        <td>〜します</td>');
document.write('        <td>〜する</td>');
document.write('        <td>〜しない</td>');
document.write('        <td>〜して</td>');
document.write('        <td>〜しろ</td>');
document.write('        <td>〜できる</td>');
document.write('        <td>〜すれば</td>');
document.write('        <td>〜しよう</td>');
document.write('        <td>〜される</td>');
document.write('        <td>〜させる</td>');
document.write('    </tr>');
document.write('');
document.write('</table>');
document.write('');
